// Generated by CoffeeScript 1.4.0
var cbname;

if (!(typeof cbname === 'function' || typeof cbname === 'undefined')) {
  throw new Error("Coffeescript Guard: Supplied value for argument cbname is not a function: " + (require('util').inspect(cbname)));
}

if (typeof cbname === 'function') {
  cbname = (function() {
    var __cbcalled, __cbref;
    __cbref = cbname;
    __cbcalled = false;
    return function() {
      if (__cbcalled) {
        throw new Error("Coffeescript Guard: Called callback (cbname) twice");
      }
      __cbcalled = true;
      return __cbref.apply(this, arguments);
    };
  })();
}
