// Generated by CoffeeScript 1.4.0
(function() {
  "use strict";
  var key, val, _ref;

  _ref = require('./coffee-script');
  for (key in _ref) {
    val = _ref[key];
    exports[key] = val;
  }

}).call(this);
